name: Example Workflow
on:
  push:

jobs:
  get-patch-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get patch content
      uses: ./.github/actions/code-review
    - name: Set up environment
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
    - name: Build and Test
      run: make test
