name: Example Workflow
on:
  push:

jobs:
  get-patch-content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get patch content
      run: |
        git diff HEAD^ HEAD > patch.diff
        cat patch.diff
